### ISSUE TITLE
Testing for None equality must be explicit

### ISSUE THREAD

**Issue by palemieux** [sandflow/ttconv#111]
Replace `bool(o)` if `bool(o is not None)` expressions

For example:

https://github.com/sandflow/ttconv/blob/bf49cc6dd85da4cec1d19fe66d5abde2be9727ec/src/main/python/ttconv/scc/content.py#L96

or

`indent if indent else 0`

**Comment by valnoel** [comment]
Commit 2438feb is also linked to this issue
