### ISSUE TITLE
Tweak Dockerfile

### ISSUE THREAD

**Issue by palemieux** [sandflow/ttconv#17]
* add comments emphasizing the intent of each of the two `RUN` lines
* break lines between `&&` commands
* use `ADD` instead of `COPY` to allow remote development

**Comment by jams008** [comment]
Hi, 
can I help optimize your Dockerfile so that the ci.sh file can autorun without adding something like this in docker run "docker run -it --rm ttconv:latest /bin/sh scripts/ci.sh"
