### ISSUE TITLE
Layout and head elements emitted even if empty

### ISSUE THREAD

**Issue by palemieux** [sandflow/ttconv#189]
See, for example, `build\imsc1\ttml\br\Br001.ttml` as emitted by the unit tests.

```
<ttml:tt xmlns:ttml="http://www.w3.org/ns/ttml" xml:lang="en">
  <ttml:head>
    <ttml:layout/>
  </ttml:head>
  <ttml:body end="00:00:10.000">
    <ttml:div end="00:00:10.000">
      <ttml:p end="00:00:10.000">
        <ttml:span>This text must be on the first line.</ttml:span>
        <ttml:br/>
        <ttml:span>This text on a second line.</ttml:span>
      </ttml:p>
    </ttml:div>
  </ttml:body>
</ttml:tt>
```

**Comment by BobBrownConsulting** [comment]
I made a fix. 

New result:

<?xml version="1.0" encoding="UTF-8"?>
<ttml:tt xmlns:ttml="http://www.w3.org/ns/ttml" xml:lang="en">
   <ttml:body end="00:00:10.000">
      <ttml:div end="00:00:10.000">
         <ttml:p end="00:00:10.000">
            <ttml:span>This text must be on the first line.</ttml:span>
            <ttml:br />
            <ttml:span>This text on a second line.</ttml:span>
         </ttml:p>
      </ttml:div>
   </ttml:body>
</ttml:tt>
