### ISSUE TITLE
SCC reader fails when {EDM} follows {RU3}

### ISSUE THREAD

**Issue by mikedo** [sandflow/ttconv#255]
ttconv fails on the the following {EDM} with "No current SCC active caption initialized"

00:00:00:00 {RCL}{0100}Hello{EDM}{}{}{EOC}
00:00:01:14 {RU3}{EDM}{CR}{1100}Bonjour

The input .scc will be provided privately.  It is ~1 minute of 3-row rollup.

**Comment by palemieux** [comment]
It looks like `{EDM}` can occur mid-line.

As a result `{EDM}` should always create a caption.
