### ISSUE TITLE
stl-reader: Background color does not change

### ISSUE THREAD

**Issue by xchange11** [sandflow/ttconv#267]
It seems that a NewBackground control code is ignored if it appears before a StartBox control code.

**Comment by palemieux** [comment]
@xchange11 What should be the background color if _StartBox_ is received without being preceded by _NewBackground_?

**Comment by palemieux** [comment]
@xchange11 Also, looking at https://github.com/sandflow/ttconv/blob/feature/add-ebu-stl-support/src/test/resources/stl/irt/requirement-0090-001.stl, which starts with the codes 02 1D 00. Doesn't that mean black (0x00) on green (0x02) background? The unit test implies that the background is black.

https://github.com/sandflow/ttconv/blob/28588b0bc3a1e0f2afb36481fef37241d0e5dabd/src/test/python/test_stl_reader.py#L227

**Comment by palemieux** [comment]
Fixed by https://github.com/sandflow/ttconv/commit/dace30b07970a62a3e4f3d45b7b00aeeeb6ca856
