### ISSUE TITLE
CEA 608 "FULL BLOCK" mapping missing?

### ISSUE THREAD

**Issue by palemieux** [sandflow/ttconv#326]
Is the mapping to "FULL BLOCK" character missing from the SCC reader?

![image](https://user-images.githubusercontent.com/4871350/131565498-86a07916-3e2e-4cf5-8733-405ce0fdb770.png)

https://github.com/sandflow/ttconv/blob/master/src/main/python/ttconv/scc/codes/special_characters.py

**Comment by valnoel** [comment]
Indeed, it seems we've missed it because it is considered as a _Standard Character_ in CTA-608:

![image](https://user-images.githubusercontent.com/1416504/131636996-0ef42b6d-5f1a-4bbf-a90f-dc0b5936417e.png)
