### ISSUE TITLE
multiple captions channels not supported

### ISSUE THREAD

**Issue by mikedo** [sandflow/ttconv#353]
If the 608 stream contains more than one caption channel (it supports 4 multiplexed channels) the conversion output is a jumble of all the channel contents. Also there is not support for the XDS data channel.  I recommend that the default be only CC1 and discard the rest of the channels 2 through 4 so that there is a valid conversion output of *some* channel.  Then add an input parameter to the conversion to select which of the 4 caption channels to transcode. Finally, for extra credit, decode the XDS language codes and populate tt@xml:lang accordingly.

**Comment by palemieux** [comment]
@mikedo It is not clear to me that the SCC format can support more than one field, which means that a given SCC file can only contain CC1 and CC2 *or* CC3 and CC4. Do you agree? If not, would you have an SCC file that contains both fields, or a different file format that does?

**Comment by mikedo** [comment]
I'm not an expert on SCC and I didn't find what I would consider authoritative documentation online.  A tool I used to extract the 4-channel 608 into SCC put the *content* for all 4 channels in the SCC file that I provided. However a professional caption tool imports it and merges the content from CC1 & CC3, and CC2 & CC4. That same professional tool cannot export more than one channel at a time, i.e. it cannot write a multi-channel SCC file.
Also the pairing you note (CC1+CC2 & CC3+CC4) doesn't make sense in practice. Due to bandwidth limitations caption channels are put on CC1 & CC3 (different fields). It's impractical to encode two robust captions in the same field.
Perhaps multiple channels in an SCC file is an uncommon thing (whether it is 2 or 4) and this is too much of edge case to invest more time on?

**Comment by palemieux** [comment]
> Perhaps multiple channels in an SCC file is an uncommon thing (whether it is 2 or 4) and this is too much of edge case to invest more time on?

That is what I am thinking... happy to be proven wrong -- ideally with a bunch of samples :)
