### ISSUE TITLE
Incorrect Color notation for RGBA with WebVTT

### ISSUE THREAD

**Issue by Voidi** [sandflow/ttconv#358]
If i have ttml file as input, which specify a color with alpha component as hexadecimal notation (for example '#ffffffc2'), this is copied verbatim to a WebVTT output.
But WebVTT uses CSS. In CSS a RGBA Color cannot be specified as hexadecimal notation. See https://www.w3.org/TR/css-color-3/#rgba-color.

Best regards
Tobias

**Comment by palemieux** [comment]
8-digit hex colors are supported in https://www.w3.org/TR/css-color-4/#hex-color, which is referenced by the [WebVTT spec](https://www.w3.org/TR/webvtt1/). Are they causing issues in practice?

**Comment by Voidi** [comment]
Thank you for this quick reply on Christmas, overlooked the wrong CSS Level.
There was another bug which prevented the correct transparency rendering in my Application, which caused my original irritation.
