### ISSUE TITLE
Add config parameter for xml:lang values in imsc_writer

### ISSUE THREAD

**Issue by jbaden** [sandflow/ttconv#373]
Many of TTCONV's supported input formats do not contain language indicators (SRT, SCC). As such, when these types of files are exported using `--otype TTML`, no language code value is provided in the document. Instead, they are exported with `xml:lang=""`, requiring edits post-export to specify the correct language code. 

Request: Would it be possible to add a config parameter in the imsc_writer to specify a BPC-47 language tag?

**Comment by palemieux** [comment]
What about making it a general option so that it is available to all writers automagically?

**Comment by palemieux** [comment]
@jbaden #374 for your review
