### ISSUE TITLE
WebVTT writer: make WebVTT cue identifiers optional

### ISSUE THREAD

**Issue by ksn-systems** [sandflow/ttconv#380]
Hi All.

I think there is a mix up in the WebTT output.

in an SRT file each caption is made up as folows
```
<caption number>
<timing details>
<caption text (one or more lines)>
<blank line>
```
currently the WebTT output is also generating 
```
<caption number>
<timing details + layout data>
<caption text (one or more lines)>
<blank line>
```
In the WebTT spec, the line before the Timing line is a "chapter number"  and can be omitted. It can also be a text like "TITLE" or "Chapter 1"
```
<chapter>
<timing details + layout data>
<caption text (one or more lines)>
<blank line>
```

**Comment by palemieux** [comment]
Can you provide an example of a WebVTT file that fails?

**Comment by ksn-systems** [comment]
Hi

Here is  the first few lines, this was derived from an SCC file via ttconv (1.0.5). The SCC is a commercial file from the US (they captioned in all caps, must be all shouting)

WEBVTT

STYLE
::cue {
  background-color: transparent;
}
::cue(.bg_black) {
  background-color: #000000ff;
}

1
00:00:03.033 --> 00:00:05.467 line:84%,start
<c.bg_black>[ DISTORTED SHOUTING ]</c>

2
00:00:19.267 --> 00:00:21.833 line:84%,start
<c.bg_black>[ CHILDREN SHOUTING ]</c>

3
00:00:53.167 --> 00:00:55.733 line:84%,start
<c.bg_black>[ SCREAMING ]</c>

4
00:01:06.167 --> 00:01:08.433 line:11%,start
<c.bg_black>MORNING, MA'AM.</c>

5
00:01:08.433 --> 00:01:11.067 line:11%,start
<c.bg_black>HAD SOME COMPLAINTS FROM</c>
<c.bg_black>THE NEIGHBORS ABOUT THE NOISE.</c>

While the file is in spec for a file that has chapter markers, they are only needed if the source file supports and has chapter markers. 

I have access to a commercial convertor that outputs the following:

WEBVTT

NOTE
Telestream Metadata
<?xml version="1.0" encoding="UTF-8"?>
<container xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.telestream.net">
  <Language xsi:type="xs:unsignedShort">21956</Language>
  <Region xsi:type="xs:unsignedShort">0</Region>
</container>


00:00:04.519 --> 00:00:04.679 align:center line:-1 position:51% size:3%
.

00:00:04.879 --> 00:00:07.120 align:center line:-2 position:50% size:55%
<i> - Previously</i>
<i> on "New Amsterdam"...</i>

00:00:07.320 --> 00:00:09.039 align:center line:-1 position:51% size:38%
<i> [tender music]</i>

**Comment by palemieux** [comment]
@ksn-systems See https://github.com/sandflow/ttconv/pull/381

**Comment by ksn-systems** [comment]
Hi, as per the spec, the line before the Timecode line is either blank or has a chapter marker.

**Comment by andreastai** [comment]
> Hi, as per the spec, the line before the Timecode line is either blank or has a chapter marker.

@ksn-systems I think this is not correct. The WebVTT spec (W3C Candidate Recommendation 4 April 2019) states the following:

> A WebVTT cue block consists of the following components, in the given order:
> Optionally, a [WebVTT cue identifier](https://www.w3.org/TR/webvtt1/#webvtt-cue-identifier) followed by a [WebVTT line terminator](https://www.w3.org/TR/webvtt1/#webvtt-line-terminator).
[WebVTT cue timings](https://www.w3.org/TR/webvtt1/#webvtt-cue-timings).

Therefore I can't see that it would be wrong to insert an identifier by default.

**Comment by chenlung** [comment]
I've used WebVTT files with and without numbers before entries. Although I personally prefer them without, I suspect the project should support both.

[Editing Tools](https://en.editingtools.io/subtitles) has an option to remove them.

**Comment by palemieux** [comment]
See revised PR which adds an option to disable cue identifiers
