### ISSUE TITLE
SCC: negative cursor leads to strange behavior

### ISSUE THREAD

**Issue by humberthardy** [sandflow/ttconv#406]
Hello,

I may have found an issue in SCCReader  

If the cursor becomes negative in `SccCaptionText.append`, old text is overwritten by the new one

Here is a test.
1. The cursor is put at row 15, col 16 and writes "Eeech!"
2. The cursor is put at col 8 on the same line (15) and writes "Scary" 

The current result is `Scary!h` instead of `Scary  Eeech!`

I am not sure if it is a bug or a bad\unauthorized SCC sequence, any thought about that?

``` 
  def test_scc_with_negative_cursor(self):
    scc_content = """Scenarist_SCC V1.0
00:00:01:00	94AE 94AE 9420 9420 94F8 94F8 45E5 E5E3 68A1 94F4 94F4 D3E3 61F2 79A1 942C 942C 942F 942F
00:00:02:00	942F 942F
    """
    scc_disassembly_expected = """\
00:00:01:00	{ENM}{ENM}{RCL}{RCL}{1516}{1516}Eeech!{1508}{1508}Scary!{EDM}{EDM}{EOC}{EOC}
00:00:02:00	{EOC}{EOC}
"""
    scc_disassembly = to_disassembly(scc_content)
    self.assertEqual(scc_disassembly_expected, scc_disassembly)
    import ttconv.srt.writer as srt_writer

    doc = to_model(scc_content)
    current_srt = srt_writer.from_model(doc)

    #bad_srt = """10:00:01,400 --> 00:00:02,033\nScary!h!\n"""
    expected_srt = """10:00:01,400 --> 00:00:02,033\nScary!  Eeech!"""
    self.assertEqual(current_srt, expected_srt)
```

**Comment by palemieux** [comment]
@humberthardy Did you try the test case with the PR at https://github.com/sandflow/ttconv/pull/395, which is a subtanstial refactor of the SCC reader?

**Comment by humberthardy** [comment]
`master` and PR #395 have the same behaviour

**Comment by humberthardy** [comment]
Thank you @valnoel, I will test it soon!

**Comment by humberthardy** [comment]
I found some errors, but, I think they are more related to the parent branch, PR #315`.
I can open issues in your repo @valnoel or, I can try to fix it too. 

Keep in mind that the main problem is (probably) a malformed SCC  :smile: 

1. There is no default style
With `ttconv/master`, if no style has been selected, we pop-on by default.
https://github.com/sandflow/ttconv/blob/b2cc10a963633e1f09682c9b5330eeddfbdbb555/src/main/python/ttconv/scc/reader.py#L220C26-L220C26
I have a scc with no RCL & RU. the whole content is lost, probably better to pop up by default than ignore it?

2 - Backspace at beginning of a line. 
SCC code : `10:01:44;17	94AE 9420 9470 9723 946E 80C1 92B0 20ec 6120 e6e9 6e20 64e5 7320 616e 6edc e573 2031 38b0 b02c 942C 8080 8080 942F` 
```
src/main/python/ttconv/scc/context.py", line 160, in backspace
    self.get_caption_to_process().get_current_text().backspace()
AttributeError: 'NoneType' object has no attribute 'backspace'
```
Easy fix: Rather than check for `get_current_text()` is not None, maybe we can comment `context.backspace()` for SccExtendedCharacter in `line.py`?

3 -Roll up with empty caption
SCC code : `10:03:20:16	94ad 94ad 9426 9426 92d0 92d0 a880 9138 9138 2064 942c 942c e575 f820 76ef e9f8 2c20 e56e 2061 6e67 ec61 e973 29ba` 
```
ttconv/scc/context.py", line 467, in process_text
    self.active_caption.append_text(word)
AttributeError: 'NoneType' object has no attribute 'append_text'
``` 

4 - Adding text with no active line
SCC code: `10:55:31:29	2080 3280 2046 3180`
```
ttconv/scc/caption_paragraph.py", line 129, in append_text
    self.get_current_line().add_text(text)
AttributeError: 'NoneType' object has no attribute 'add_text'
```

**Comment by valnoel** [comment]
@humberthardy Thanks for the feedback.

I wasn't sure we wanted to make the SCC reader resilient or constraining regarding the CEA-608 specification until we discuss with @palemieux...
So I've updated #395 with [e749eb9](https://github.com/sandflow/ttconv/pull/395/commits/e749eb986142d1e933d2b9a743355502c605c283) to make the SCC parsing less restrictive and to handle your cases.

Could you please check if this works for you at this point? Thanks!

**Comment by humberthardy** [comment]
Thanks @valnoel for your amazing work, it seems to work better.
I've tested it blind on over a thousand SCCs and it seems to work 99% of the time. 
I still have a few errors (~ 10) I don't know if it's worth fixing it.
I've identified a few, if your are insterested, you can find them below.
The last one is probably the most interesting: we are switching from popon to rollup, the SCCContext is in rollup style but the current paragraph still in Popon style leading to a runtime error.
```

**Comment by valnoel** [comment]
@humberthardy I've updated [my PR](https://github.com/sandflow/ttconv/pull/395), addressing the last cases you posted. Could you please have a look at it? Thanks!

**Comment by humberthardy** [comment]
I no longer see any python runtime errors.
Thank you very much @valnoel

**Comment by palemieux** [comment]
Closed by https://github.com/sandflow/ttconv/pull/395
