### ISSUE TITLE
VTT: add support for TextAlign

### ISSUE THREAD

**Issue by ngaullier** [sandflow/ttconv#407]
My use case is "STL in to VTT out".
The STL parser seems to implement JC -> TextAlignType, but the TextAlignType is not taken into account by the VTT writer...
Thank you!
Nicolas

**Comment by palemieux** [comment]
How broadly is [`align`](https://www.w3.org/TR/webvtt1/#webvtt-cue-line-alignment) supported by WebVTT players?

**Comment by ngaullier** [comment]
The only one thing I know for sure, is that iOS devices in France do support align and it makes it possible to support SDH which is somewhat required by CSA. I don' know about broader support in browsers or so.

**Comment by palemieux** [comment]
I think we need to make sure that adding `align` would not break other VTT players.

**Comment by palemieux** [comment]
... or alternatively we put support for `align` behind a flag.

**Comment by ngaullier** [comment]
Indeed, my PR is based on a "text_position" configuration item. Naming is always the biggest thing, so let me know of course...

**Comment by palemieux** [comment]
Closed by https://github.com/sandflow/ttconv/commit/ecec1faf39e15a2a1ce5571ebd66204a16382354
